### ISSUE TITLE
cuda errpr

### ISSUE THREAD

**Issue by zachysaur** [ShineChen1024/MagicClothing#52]
(magicloth) F:\MagicClothing-main>python gradio_generate.py --model_path F:\MagicClothing-main\checkpoints\ipadapter_faceid --enable_cloth_guidance
C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Loading pipeline components...:  20%|████▊                   | 1/5 [00:00<00:03,  1.08it/s]C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Loading pipeline components...: 100%|████████████████████████| 5/5 [00:01<00:00,  3.43it/s]
Traceback (most recent call last):
  File "F:\MagicClothing-main\gradio_generate.py", line 25, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance)
  File "F:\MagicClothing-main\garment_adapter\garment_diffusion.py", line 20, in __init__
    self.pipe = sd_pipe.to(self.device)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 869, in to
    module.to(device, dtype)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
    param_applied = fn(param)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\ggrov\anaconda3\envs\magicloth\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(magicloth) F:\MagicClothing-main>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by ShineChen1024** [comment]
maybe you install a cpu version of torch, try to use gpu version

**Comment by zachysaur** [comment]
i have still i am getting this error

**Comment by ArtemKhrom0v** [comment]
Hi
I get exactly the same error

![Снимок экрана 2024-04-24 214753](https://github.com/ShineChen1024/MagicClothing/assets/88584600/8cdb8ce6-22be-4d87-8198-84881c5011e4)

**Comment by ShineChen1024** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
