### ISSUE TITLE
help  ----No checkpoints at given path----

### ISSUE THREAD

**Issue by eileenw1017** [ShineChen1024/MagicClothing#57]
the log is :

(magicloth) /mnt/workspace/workgroup/yunke/MagicClothing> python gradio_generate.py --model_path /mnt/workspace/workgroup/yunke/MagicClothing/checkpoints/magic_clothing_768_vitonhd_joint.safetensors --enable_cloth_guidance
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.37it/s]
----No checkpoints at given path----
Traceback (most recent call last):
  File "/mnt/workspace/workgroup/yunke/MagicClothing/gradio_generate.py", line 25, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance)
  File "/mnt/workspace/workgroup/yunke/MagicClothing/garment_adapter/garment_diffusion.py", line 36, in __init__
    self.set_seg_model()
  File "/mnt/workspace/workgroup/yunke/MagicClothing/garment_adapter/garment_diffusion.py", line 41, in set_seg_model
    self.seg_net = load_seg_model(checkpoint_path, device=self.device)
  File "/mnt/workspace/workgroup/yunke/MagicClothing/garment_seg/process.py", line 96, in load_seg_model
    net = net.to(device)
AttributeError: 'NoneType' object has no attribute 'to'

**Comment by poomshift** [comment]
already downloaded cloth_segm.pth. still got the same error
