### ISSUE TITLE
Error in  gradio_cloth_inpainting.py earlyAccess branch

### ISSUE THREAD

**Issue by vinay1331** [ShineChen1024/MagicClothing#71]
Getting below error when trying out gradio_cloth_inpainting.py

 UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Traceback (most recent call last):
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/gradio/utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "/home/vinay/magicclothing/MagicClothing/gradio_cloth_inpainting.py", line 40, in process
    images, cloth_mask_image = full_net.generate(cloth_image, cloth_mask_image, prompt, a_prompt, num_samples, n_prompt, seed, scale, cloth_guidance_scale, sample_steps, height, width, image=person_image,mask_image=person_mask,control_image=control_img)
  File "/home/vinay/magicclothing/MagicClothing/garment_adapter/garment_diffusion.py", line 99, in generate
    images = self.pipe(
  File "/home/vinay/anaconda3/envs/magicloth/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vinay/magicclothing/MagicClothing/pipelines/VirtualTryOnPipeline.py", line 189, in __call__
    self.check_inputs(
TypeError: StableDiffusionControlNetInpaintPipeline.check_inputs() takes from 6 to 13 positional arguments but 16 were given

**Comment by ShineChen1024** [comment]
check diffusers version, now i am working on 0.26.3 which is ok

**Comment by ShineChen1024** [comment]
![image](https://github.com/ShineChen1024/MagicClothing/assets/16463912/91816b87-23c4-43fe-866f-0386c763f913)
![image](https://github.com/ShineChen1024/MagicClothing/assets/16463912/cb1595ec-92d4-497f-8000-ed7939c77bf4)

**Comment by algorithmconquer** [comment]
why the output looks like person image?
![Uploading ME1714032378255.png…]()

**Comment by ShineChen1024** [comment]
Can't see your image.broken?

**Comment by vinay1331** [comment]
Thanks @ShineChen1024 this worked with 0.26.3 can you please help me with the trained weights you are using along with advanced parameters.

**Comment by Aukture** [comment]
@ShineChen1024  how do u get so good results? i'm not able to get even close.

**Comment by g4ur4vs** [comment]
same here, the outfit in output image is not even close to the input cloth!!

**Comment by g4ur4vs** [comment]
also can you pls add which model to use for each gradio file, its really confusing. Thanks in advance : ) !!
