### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by 1LucasGraham** [ShineChen1024/MagicClothing#98]
![image](https://github.com/user-attachments/assets/3459ab7f-ec7d-4238-b21c-d365df99b4a3)

```
(magicloth) root@c13f61dbcdc0:/workspace# python /workspace/MagicClothing/inference.py --cloth_path /workspace/images/model_cloth.jpg --model_path /workspace/MagicClothing/checkpoints/magic_clothing_768_vitonhd_joint.safetensors --output_path /workspace/images/model_output.jpg
/root/anaconda3/envs/magicloth/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  5.21it/s]
----No checkpoints at given path----
Traceback (most recent call last):
  File "/workspace/MagicClothing/inference.py", line 38, in <module>
    full_net = ClothAdapter(pipe, args.model_path, device, args.enable_cloth_guidance, False)
  File "/workspace/MagicClothing/garment_adapter/garment_diffusion.py", line 39, in __init__
    self.set_seg_model()
  File "/workspace/MagicClothing/garment_adapter/garment_diffusion.py", line 44, in set_seg_model
    self.seg_net = load_seg_model(checkpoint_path, device=self.device)
  File "/workspace/MagicClothing/garment_seg/process.py", line 96, in load_seg_model
    net = net.to(device)
AttributeError: 'NoneType' object has no attribute 'to'
(magicloth) root@c13f61dbcdc0:/workspace#
```

**Comment by 1LucasGraham** [comment]
@ShineChen1024 
cloth_segm.pth and magic_clothing_768_vitonhd_joint.safetensors downloaded 
in `/workspace/MagicClothing/checkpoints/`

**Comment by 1LucasGraham** [comment]
> @ShineChen1024 cloth_segm.pth and magic_clothing_768_vitonhd_joint.safetensors downloaded in `/workspace/MagicClothing/checkpoints/`

please help me!
